[package]
name = "flashdb-rs"
version = "0.0.1"
edition = "2021"

[build-dependencies]
cc = "1.2.26"
bindgen = "0.72.0"

[dev-dependencies]
tempfile = "3.4.0"
rand = "0.8.5"
assert_cmd = "2.0.17"
anyhow = "1.0.98"

[dependencies]
embedded-io = "0.6.1"
log = { version = "0.4.27", optional = true }
lru = { version = "0.12.3", optional = true }
thiserror = "2.0.12"

[features]
default = ["kvdb", "tsdb", "log", "time64", "std"]
kvdb = []
tsdb = []
time64 = []
std = ["embedded-io/std", "dep:lru"]
log = ["dep:log"]
